### ISSUE TITLE
Add api endpoint electricvehicle

### ISSUE THREAD

**Issue by apfelflo89** [xraver/mercedes_me_api#12]
Hi, 

thanks for your work, would it be possible to add the api endpoint electicvehicle to get the informations for hybrids too?

Specs can be found here: 
https://developer.mercedes-benz.com/products/electric_vehicle_status/specifications/electric_vehicle_status_api

**Comment by xraver** [comment]
Dear
your suggestion is very great.
let me find time to study this API and integrate it if it would be possible!
any suggestion to improve my work is very welcome! thanks

**Comment by xraver** [comment]
Dear
I've tried to add this feature.
unfortunately I don't have an electric car and I cannot check if it works properly.
I leave this issue opened as far I receive the evidence of proper working.
If you have chance to test it it would be very helpfull!

**Comment by apfelflo89** [comment]
Hey, it works for me, thank you!

**Comment by xraver** [comment]
Great news! I close the issue.
In case you will find some issue related to this API feel free to contact me!
