### ISSUE TITLE
Do you want me to add an all-in-one GitHub action?

### ISSUE THREAD

**Issue by KTibow** [xraver/mercedes_me_api#14]
If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that.
- Do you want to enable auto-formatting?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by xraver** [comment]
Dear
thank for your proposal.
every kind of help in my project is more than welcome.
I'm not familiar with github action... can you explain me what improved are you able to provide to this project?
thanks

**Comment by KTibow** [comment]
When you accept my PR, it'll add a section to the top of your repo, Actions. The GitHub Action can automatically format your code, so it looks nicer, and is easier to understand. It also can automatically send you an email if you write invalid code without realizing. And finally, it can give you suggestions for how to improve your code's style.

**Comment by xraver** [comment]
this is very nice feature!
thanks
very welcome

Il giorno dom 20 dic 2020 alle ore 23:38 Kendell R <notifications@github.com>
ha scritto:

**Comment by xraver** [comment]
Dear, you have done a very great job!
you have merged my old action from hacs with this new one.
thank you very much!
when i'll have time i'll study git actions :) seems are very powerfull
