### ISSUE TITLE
Add API endpoint "Pay As You Drive Insurance"

### ISSUE THREAD

**Issue by Siddhant-k** [xraver/mercedes_me_api#18]
Hello! Thanks for a very useful setup here. I was wondering if it is possible to add Pay As You Drive Insurance API. It allows to get the odometer reading which will be very useful for a complete info package. More details can be found here: 
[Pay As You Drive Insurance API](https://developer.mercedes-benz.com/products/pay_as_you_drive_insurance)

**Comment by danielrheinbay** [comment]
@Siddhant-k , does this work for you?
Please note:
* you need to get a new token (as the scope has increased)
* you need to re-generate your resources file (i.e. delete the one you have)
