### ISSUE TITLE
Token File missing - Creating a new one

### ISSUE THREAD

**Issue by ehallq** [xraver/mercedes_me_api#22]
Even though I create a .mercedesme_token file with data from (copy/paste) from my pc where I ran the python script to get the token. I get this error (Token File missing - Creating a new one) followed by "Error creating token" when restarting home assistant. I also have the .mercedesme_config file with client id etc

**Comment by derekoharrow** [comment]
Have you placed the file in the home assistant config directory (where you're configuration.yaml is)?

**Comment by ehallq** [comment]
Thanks that helped. Your readme says hacs folder, and I though that was the mercedesmeapi folder that hacs created

> Please use the other script to retrieve the first token and copy it into hacs folder (.mercedesme_token)

**Comment by xraver** [comment]
Thanks. I have to change the readme to make it more clear

Il giorno lun 4 gen 2021 alle 20:11 ehallq <notifications@github.com> ha
scritto:
