### ISSUE TITLE
Cannot create token file following instructions

### ISSUE THREAD

**Issue by user897943** [xraver/mercedes_me_api#26]
I followed the instructions on the front page. It does not work. My browser states:
This site can’t be reached - localhost refused to connect.

I noticed that the callback url is https://localhost

I tried to change to my external URL for homeassistant, it just loads the HA dashboard if I press enter with my external URL - I also changed to the external URL on the MME dev portal under the Oauth section.

What am I missing? This is really poorly documented.

**Comment by user897943** [comment]
I think I figured it - on bash, just below the URL it said "copy code from URL". I noticed after the https://localhost the URL contained a code, I copied just the code without the ?code= part, and pasted into the shell, then enter and then it did something. I transferred the .mercedesme_token file inside the home assistant /config folder along with the configuration.yaml from home assistant. Now I get sensors such as sensor.mycarVIN_odo. I get several of these sensors however their state is all "unknown". What's the issue now?

**Comment by danielrheinbay** [comment]
Yes, copying the code from the URL is the way to go.
Do you get readings using the bash or Python scripts (without HASS)?

If you have only recently subscribed to the BYOC APIs, you may need to actually use your car to get some readings.

**Comment by xraver** [comment]
Dear,
i've updated the readme... hope this is more clear now. if not feel free to write here again

**Comment by user897943** [comment]
Very nice!! Now the instructions are much clearer. Thank you for reacting to my feedback so quickly and thanks for working on this component.

**Comment by user897943** [comment]
> Yes, copying the code from the URL is the way to go.
> Do you get readings using the bash or Python scripts (without HASS)?
> 
> If you have only recently subscribed to the BYOC APIs, you may need to actually use your car to get some readings.

I drove for three hours today, unfortunately no change, I was reading some comments on other issues here and I even downgraded to 0.9 but it makes no difference. I made sure to subscribe to all APIs and to log out of everything (cleared all cookies). I saw the prompt to select all the APIs and clicked Allow on the application, then copied the code into the script, then I copied the .mercedesme_token file into the same folder as my configuration.yaml and restarted. I get sensor.myvin_blabla but the status is unknown. I get all the relevant sensors and they all have "unknown". Do you know if you have to pay for the Mercedes Me subscription to get this data? I know you have to pay for the app to let you lock/unlock the car for example but to just get the info from the car do you have to pay Mercedes the subscription? I am under the impression that they collect this info and if you're using BYOCAR on the API you can get the data for free!?
