### ISSUE TITLE
Entities not created

### ISSUE THREAD

**Issue by LukasVice** [xraver/mercedes_me_api#27]
Hi,
I installed the component with HACS, updated the configuration and put the token into the designated file.
But unfortunately I can't see any entitites. Is there an additional step to get all the entities in HA?
Thank you!

**Comment by andilge** [comment]
+1 for this question. Logs now show no error, component starts up flawlessly but there is no entity at all is showing up in HA.

**Comment by LukasVice** [comment]
It works for me now - don't know why. Search in your entities for you vehicle id.

**Comment by andilge** [comment]
might work after a certain delay only, will try again later.
