### ISSUE TITLE
electric car states bad scope

### ISSUE THREAD

**Issue by apfelflo89** [xraver/mercedes_me_api#30]
I´m getting errors while using the .sh script. Receiving a token works.
Scope is default to your script:
`scope=mb:vehicle:mbdata:fuelstatus%20mb:vehicle:mbdata:vehiclestatus%20mb:vehicle:mbdata:vehiclelock%20mb:vehicle:mbdata:evstatus%20mb:vehicle:mbdata:payasyoudrive%20offline_access`

The electric car parameter then ends up with the following error. 
`./mercedes_me_api.sh -e`
`mercedes_me_api.sh - 0.6`

`Retrieving soc:`
`{"exVeErrorId":"4","exVeErrorMsg":"Bad Scope","exVeErrorRef":"8fcf40f3-1dfe-4d25-9bf3-675b0de54387"}`
`Retrieving rangeelectric:`
`{"exVeErrorId":"4","exVeErrorMsg":"Bad Scope","exVeErrorRef":"5f8a4742-25b9-445f-9a13-0a7b089e58b8"}`

Is it only me? Other endpoints like status, odometer or lock work, did mercedes change a scope within the api?

**Comment by apfelflo89** [comment]
OK since there are no real responses to the issues, I´m better off using [https://github.com/ReneNulschDE/mbapi2020](https://github.com/ReneNulschDE/mbapi2020) which appears to be the better candidate for using the cars data.

**Comment by xraver** [comment]
Hi,
sorry for the delay.
for sure René implementation works very well and seems very fast-reactive.
my implementation is based on Mercedes official api still in development.

I've tried again and seems working. I'm receiving no data becasue of my car is not equipped.
Could you try to create again your mercedes me app and get back your token?
thanks
