### ISSUE TITLE
Error 504 after retrieving token and trying to get resources

### ISSUE THREAD

**Issue by sawfear** [xraver/mercedes_me_api#31]
I´m getting errors when trying to fetch the available resources. Token retrieval works flawless. Error in python script from my PC and HA correlate.

Error:

python.exe .\mercedes_me_api.py -s
Error retrieving available resources - Generic Error (504)
Error retrieving available resources
Error retrieving resource list.
Error initializing resources

I´m guessing Error 504 is a bad Gateway error. Do others also have problems with the connection at the moment?

I also recreated the app in the developer portal but the issue still remains.

Any help would be much appreciated.

**Comment by pierniq** [comment]
There is problem with API.
They are working on it... I've got this info from Mercedes-Benz developers team.

Issue to close.

**Comment by xraver** [comment]
Yes
same problem here.
try later
