### ISSUE TITLE
Upgrade to new token and authentication method

### ISSUE THREAD

**Issue by samfaitmalomolet** [xraver/mercedes_me_api#34]
Since 2nd of november 2022, the way to retrive token and authenticate as evolved.
I have on a local branch the required changes to take into account those changes.
@xraver let me know if you want me to push the branch and create a pull request or if you want to have the files updated that you will integrate yourself.
https://developer.mercedes-benz.com/content-page/migration_2022

**Comment by xraver** [comment]
Will be great!! Thanks you!!

Il Sab 12 Nov 2022, 15:42 samfaitmalomolet ***@***.***> ha
scritto:

**Comment by samfaitmalomolet** [comment]
What do you prefer then ? code files or you let me create a PR ? ( for the moment, I have not the right)

**Comment by xraver** [comment]
Thanks for the good work!!
