### ISSUE TITLE
Unable to login for first token

### ISSUE THREAD

**Issue by bvzasfb** [xraver/mercedes_me_api#38]
The links generated by both python and bash scripts are dectected as "wrong" by mercedes.

Instead of a login page I get

Bad Request
Unregistered redirect_uri ("https://localhost").

**Comment by harrolf** [comment]
@bvzasfb Can you check if you have **https** configured in you mercedes project, by default I think it's **http**

**Comment by bvzasfb** [comment]
That was it.
I added https://localhost to the redirect urls and now it works.
